### ISSUE TITLE
Should we refactor to decouple logic and view?

### ISSUE THREAD

**Issue by Armienn** [camerongillette/factorio_blueprint_editor#16]
Right now there's some heavy coupling, which makes the code harder to reason about. Anyone up for an attempt at some restructuring? Any comments about stuff that should be taken into consideration, etc?

**Comment by palexcast** [comment]
I agree, we should also probably split up the javascript into logical entities of some kind?

**Comment by ryepup** [comment]
https://github.com/demipixel/factorio-blueprint/ looks to have a nice object model for the logic side of things.

**Comment by Zeragamba** [comment]
Aye, we should decouple this stuff

**Comment by Armienn** [comment]
At a quick glance, https://github.com/demipixel/factorio-blueprint/ might almost be the entire logic side we need. I'm not sure about the proper way to include other projects, though. Do anyone else have experience with that, or should we just play it by ear?

**Comment by ryepup** [comment]
Most large frontend projects have a build process that handles this sort of thing. I have experience with it and could set it up, but it would make it harder for newer developers to start working on the project.  Instead of "edit the files and refresh", contributors would need to install a bunch of tools on their computer and learn how to use them.

Long term this is worth it because it makes it easy to add tests, linters (as desired in #18), split code amongst multiple files, reduce the size of the final file for faster downloads, safely use ES6 language features without fear of IE, etc.

On the other hand, this seems like a really fun project, and it keeping it simple would let more people contribute.

We can use libraries and stave off the complexity of a build step by using the [unpkg](https://unpkg.com) service, which would let us use libraries from `<script>` tags, but factorio-blueprint would need to make a few changes to their build process to get in there.

**Comment by demipixel** [comment]
Autotorio compiles it pretty effortlessly so I'd take a look at that.

As for "including it", I added a license to ease worries and I really want to encourage people to use it, just try not to sell factorio-blueprint itself or copy it and say it's your own without making any changes.

Easiest method will probably be a script that downloads/updates factorio-blueprint (and other dependencies you might want) and then compiles everything together in one file.

**Comment by lessthantrue** [comment]
I'm not familiar with how github projects work, but it seems like this feature would be well suited for it so we know what kind of progress is being made. Could someone with write access look into that?

**Comment by Zeragamba** [comment]
Github projects is very simliar to an agile board

**Comment by lessthantrue** [comment]
The reason I ask is because I have some features in mind that should be waited on until we clean this up a bit, but I don't know who (if anyone) is working on this and what progress they've made. I also don't want to start this myself and have two different people solving the same problem two different ways if someone else is working on it.

Maybe start a new branch in this repository for this feature, so it can be worked on more collaboratively?

**Comment by ryepup** [comment]
Spent a little time looking at factorio-blueprint and the existing codebase, thinking about how to break this up to permit multiple views (#25).

Two options are jumping to mind:

* we could pull in React/Vue/Angular; those all have very well-worn patterns for decoupling logic and view. I'm thinking that might be overkill, and it'd need to wait until after travis-ci is setup anyhow
* implement a classic [model-view-controller (MVC)](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) or [model-view-viewmodel (MVVM)](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel) architecture in vanilla js,  with a few utility libraries

I like react, but it's got a hell of a learning curve, which makes me lean towards MVVM. The model is `factorio-blueprint`, the view-model is a fairly thin wrapper, and the views are more js functions that accept the view-model as input and return html (i.e. components).

Thoughts?

**Comment by lessthantrue** [comment]
Considering the scale of the project, option 2 seems best. We don't need much extra for now, just a better way of organizing things.

If we plan on going full Model <=> something <=> view, it would be worth it to look into using some kind of template engine to make the conversion from the model easier.

**Comment by Zeragamba** [comment]
+1 for option 2 as well. For now we're trying to avoid having people install Node and NPM to contribute to the project.
